#!/bin/sh

if [ $# -ne 3 ]; then
    echo "Usage: $0 input outfile audioch"
    exit
fi

input=$1
output=$2
audioch=$3
options="-H 10"
options+=" -a $audioch"
options+=" -x vob"
options+=" -b 128,0,2"
options+=" --a52_drc_off"
options+=" -f 30,4"
options+=" -M 2"
#options+=" -Y 12,0,12,0"
#options+=" -Z 720x406"
options+=" -export_par 118,100"
options+=" -y xvid"
options+=" -w 9000,50"
echo "Start transcode $input -> $output (pass 1)"
transcode -i "$input" -o "$output" -R 1 $options
echo "Start transcode $input -> $output (pass 2)"
transcode -i "$input" -o "$output" -R 2 $options
